import { PrismaClient, ProductCategory, PriceType } from '@prisma/client'

const prisma = new PrismaClient()

const products = [
  // ==================== BOX PARA BANHEIRO (15 produtos) ====================
  {
    name: 'Box de Vidro Premium',
    slug: 'box-vidro-premium',
    description:
      'Box sob medida com vidro temperado 8mm de alta qualidade, perfis em alumínio anodizado e acabamento impecável. Ideal para banheiros modernos e sofisticados.',
    shortDescription: 'Box sob medida com vidro temperado 8mm, acabamento premium',
    category: ProductCategory.BOX,
    images: ['/images/products/box-premium.jpg'],
    thumbnail: '/images/products/box-premium.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 2490,
    priceRangeMax: 4890,
    colors: ['Incolor', 'Verde', 'Fumê', 'Bronze'],
    finishes: ['Alumínio Anodizado', 'Perfil Preto Fosco'],
    thicknesses: ['8mm', '10mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Box Incolor Padrão',
    slug: 'box-incolor-padrao',
    description:
      'Box com vidro temperado 8mm incolor, acabamento padrão de alta qualidade. Ótima relação custo-benefício para seu banheiro.',
    shortDescription: 'Box vidro temperado 8mm incolor, ótimo custo-benefício',
    category: ProductCategory.BOX,
    images: ['/images/products/box-incolor.jpg'],
    thumbnail: '/images/products/box-incolor.jpg',
    priceType: PriceType.FIXED,
    basePrice: 1890,
    priceRangeMin: 1890,
    colors: ['Incolor'],
    finishes: ['Alumínio Branco', 'Alumínio Natural'],
    thicknesses: ['8mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Box de Canto',
    slug: 'box-de-canto',
    description:
      'Box de canto com porta de abrir, vidro temperado 8mm. Aproveitamento ideal para banheiros pequenos e médios.',
    shortDescription: 'Box de canto porta de abrir, vidro temperado 8mm',
    category: ProductCategory.BOX,
    images: ['/images/products/box-canto.jpg'],
    thumbnail: '/images/products/box-canto.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 2190,
    priceRangeMax: 3490,
    colors: ['Incolor', 'Verde', 'Fumê'],
    finishes: ['Dobradiças Premium'],
    thicknesses: ['8mm', '10mm'],
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Box Articulado 2 Folhas',
    slug: 'box-articulado-2-folhas',
    description:
      'Box com abertura articulada em 2 folhas, sistema premium de dobra. Ideal para banheiros médios.',
    shortDescription: 'Box articulado 2 folhas, abertura premium',
    images: ['/images/products/box-articulado-2-folhas.jpg'],
    thumbnail: '/images/products/box-articulado-2-folhas.jpg',
    category: ProductCategory.BOX,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 2890,
    priceRangeMax: 4290,
    colors: ['Incolor', 'Fumê', 'Verde'],
    finishes: ['Perfil Preto', 'Perfil Cromado'],
    thicknesses: ['8mm'],
    isActive: true,
  },
  {
    name: 'Box Frontal 2 Folhas',
    slug: 'box-frontal-2-folhas',
    description:
      'Box frontal com 2 folhas de correr, vidro temperado e trilho de alumínio de alta qualidade.',
    shortDescription: 'Box frontal 2 folhas de correr',
    images: ['/images/products/box-frontal-2-folhas.jpg'],
    thumbnail: '/images/products/box-frontal-2-folhas.jpg',
    category: ProductCategory.BOX,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 1990,
    priceRangeMax: 2990,
    colors: ['Incolor', 'Fumê', 'Bronze'],
    finishes: ['Trilho Alumínio'],
    thicknesses: ['8mm'],
    isActive: true,
  },
  {
    name: 'Box Frontal 4 Folhas',
    slug: 'box-frontal-4-folhas',
    description:
      'Box frontal com 4 folhas de correr, ideal para banheiros grandes. Sistema premium de deslizamento.',
    shortDescription: 'Box frontal 4 folhas, sistema premium',
    images: ['/images/products/box-frontal-4-folhas.jpg'],
    thumbnail: '/images/products/box-frontal-4-folhas.jpg',
    category: ProductCategory.BOX,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 3490,
    priceRangeMax: 5290,
    colors: ['Incolor', 'Fumê'],
    finishes: ['Trilho Reforçado'],
    thicknesses: ['8mm', '10mm'],
    isActive: true,
  },
  {
    name: 'Box Elegance Premium',
    slug: 'box-elegance-premium',
    description:
      'Linha top de box com vidro temperado 10mm, perfil minimalista e ferragens importadas. O melhor em acabamento.',
    shortDescription: 'Box linha premium, perfil minimalista e ferragens importadas',
    images: ['/images/products/box-elegance-premium.jpg'],
    thumbnail: '/images/products/box-elegance-premium.jpg',
    category: ProductCategory.BOX,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 5500,
    priceRangeMax: 9500,
    colors: ['Incolor', 'Low Iron'],
    finishes: ['Perfil Preto Fosco', 'Perfil Cromado Escovado'],
    thicknesses: ['10mm', '12mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Box para Banheira',
    slug: 'box-para-banheira',
    description:
      'Box especial para banheira com vidro temperado e sistema de dobra ou correr. Sob medida.',
    shortDescription: 'Box para banheira, sob medida',
    images: ['/images/products/box-para-banheira.jpg'],
    thumbnail: '/images/products/box-para-banheira.jpg',
    category: ProductCategory.BOX,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 2890,
    priceRangeMax: 5890,
    colors: ['Incolor', 'Fumê', 'Verde'],
    finishes: ['Sistema de Dobra', 'Sistema de Correr'],
    thicknesses: ['8mm'],
    isActive: true,
  },
  {
    name: 'Box Cristal com Dobradiças',
    slug: 'box-cristal-dobradicas',
    description:
      'Box com dobradiças em aço inox e vidro cristal temperado. Design clean e moderno.',
    shortDescription: 'Box dobradiças inox, vidro cristal',
    images: ['/images/products/box-cristal-dobradicas.jpg'],
    thumbnail: '/images/products/box-cristal-dobradicas.jpg',
    category: ProductCategory.BOX,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 2690,
    priceRangeMax: 4190,
    colors: ['Incolor'],
    finishes: ['Dobradiças Inox Polido', 'Dobradiças Inox Escovado'],
    thicknesses: ['8mm', '10mm'],
    isActive: true,
  },
  {
    name: 'Box Comum Tradicional',
    slug: 'box-comum-tradicional',
    description:
      'Box tradicional com abertura frontal, vidro temperado 8mm. Solução econômica e de qualidade.',
    shortDescription: 'Box tradicional abertura frontal, econômico',
    category: ProductCategory.BOX,
    priceType: PriceType.FIXED,
    basePrice: 1590,
    priceRangeMin: 1590,
    colors: ['Incolor'],
    finishes: ['Perfil Branco'],
    thicknesses: ['8mm'],
    isActive: true,
  },

  // ==================== ESPELHOS (10 produtos) ====================
  {
    name: 'Espelho com LED Integrado',
    slug: 'espelho-led-integrado',
    description:
      'Espelho decorativo premium com iluminação LED de alta eficiência energética, sensor touch e função antiembaçante. Perfeito para banheiros modernos.',
    shortDescription: 'Espelho LED, sensor touch e antiembaçante',
    category: ProductCategory.ESPELHOS,
    images: ['/images/products/espelho-led.jpg'],
    thumbnail: '/images/products/espelho-led.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 890,
    priceRangeMax: 2490,
    colors: ['Incolor'],
    finishes: ['LED Branco Frio', 'LED Branco Quente', 'LED Bivolt'],
    thicknesses: ['5mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Espelho Bisotado',
    slug: 'espelho-bisotado',
    description:
      'Espelho com acabamento bisotado de 2cm em toda borda. Elegância clássica para qualquer ambiente.',
    shortDescription: 'Espelho bisotê 2cm, elegância clássica',
    category: ProductCategory.ESPELHOS,
    images: ['/images/products/espelho-bisotado.jpg'],
    thumbnail: '/images/products/espelho-bisotado.jpg',
    priceType: PriceType.PER_M2,
    pricePerM2: 450,
    priceRangeMin: 450,
    priceRangeMax: 650,
    colors: ['Incolor', 'Bronze'],
    finishes: ['Bisotê 2cm', 'Bisotê 3cm'],
    thicknesses: ['4mm', '6mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Espelho Bronze',
    slug: 'espelho-bronze',
    description: 'Espelho bronze para decoração sofisticada. Tom quente e elegante.',
    shortDescription: 'Espelho bronze, decoração sofisticada',
    category: ProductCategory.ESPELHOS,
    priceType: PriceType.PER_M2,
    pricePerM2: 480,
    colors: ['Bronze'],
    finishes: ['Polido'],
    thicknesses: ['4mm', '6mm'],
    isActive: true,
  },
  {
    name: 'Espelho Fumê',
    slug: 'espelho-fume',
    description: 'Espelho fumê para ambientes modernos. Efeito sofisticado e diferenciado.',
    shortDescription: 'Espelho fumê, efeito sofisticado',
    category: ProductCategory.ESPELHOS,
    priceType: PriceType.PER_M2,
    pricePerM2: 490,
    colors: ['Fumê'],
    finishes: ['Polido'],
    thicknesses: ['4mm'],
    isActive: true,
  },
  {
    name: 'Espelho Guardian 4mm',
    slug: 'espelho-guardian-4mm',
    description: 'Espelho Guardian de alta qualidade, 4mm. Padrão internacional de excelência.',
    shortDescription: 'Espelho Guardian 4mm, alta qualidade',
    images: ['/images/products/espelho-guardian-4mm.jpg'],
    thumbnail: '/images/products/espelho-guardian-4mm.jpg',
    category: ProductCategory.ESPELHOS,
    priceType: PriceType.PER_M2,
    pricePerM2: 420,
    colors: ['Incolor'],
    finishes: ['Bordas Polidas'],
    thicknesses: ['4mm'],
    isActive: true,
  },
  {
    name: 'Espelho Guardian 6mm',
    slug: 'espelho-guardian-6mm',
    description: 'Espelho Guardian 6mm, maior durabilidade e resistência. Ideal para áreas úmidas.',
    shortDescription: 'Espelho Guardian 6mm, extra resistente',
    images: ['/images/products/espelho-guardian-6mm.jpg'],
    thumbnail: '/images/products/espelho-guardian-6mm.jpg',
    category: ProductCategory.ESPELHOS,
    priceType: PriceType.PER_M2,
    pricePerM2: 520,
    colors: ['Incolor'],
    finishes: ['Bordas Polidas'],
    thicknesses: ['6mm'],
    isActive: true,
  },
  {
    name: 'Espelho Decorativo Veneziano',
    slug: 'espelho-decorativo-veneziano',
    description:
      'Espelho veneziano com design artístico. Peça de destaque para decoração sofisticada.',
    shortDescription: 'Espelho veneziano, design artístico',
    category: ProductCategory.ESPELHOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 1500,
    priceRangeMax: 4500,
    colors: ['Incolor', 'Bronze'],
    finishes: ['Artesanal'],
    thicknesses: ['6mm'],
    isActive: true,
  },

  // ==================== GUARDA-CORPO (11 produtos) ====================
  {
    name: 'Guarda-Corpo de Vidro com Botões',
    slug: 'guarda-corpo-vidro-botoes',
    description:
      'Guarda-corpo em vidro laminado 10mm com fixação por botões de inox. Segurança máxima combinada com design minimalista e elegante.',
    shortDescription: 'Guarda-corpo laminado 10mm, fixação botões inox',
    category: ProductCategory.GUARDA_CORPO,
    images: ['/images/products/guarda-corpo.jpg'],
    thumbnail: '/images/products/guarda-corpo.jpg',
    priceType: PriceType.PER_M2,
    pricePerM2: 890,
    priceRangeMin: 890,
    priceRangeMax: 1290,
    colors: ['Incolor', 'Verde', 'Fumê'],
    finishes: ['Botões Inox Polido', 'Botões Inox Escovado'],
    thicknesses: ['10+10mm laminado'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Guarda-Corpo Misto (Vidro + Inox)',
    slug: 'guarda-corpo-misto-inox',
    description:
      'Guarda-corpo com vidro laminado e corrimão em aço inox. Design moderno e seguro para sacadas e escadas.',
    shortDescription: 'Guarda-corpo vidro + corrimão inox',
    category: ProductCategory.GUARDA_CORPO,
    images: ['/images/products/guarda-corpo-inox.jpg'],
    thumbnail: '/images/products/guarda-corpo-inox.jpg',
    priceType: PriceType.PER_M2,
    pricePerM2: 1190,
    priceRangeMin: 1190,
    priceRangeMax: 1690,
    colors: ['Incolor', 'Verde'],
    finishes: ['Inox Polido', 'Inox Escovado'],
    thicknesses: ['10+10mm laminado'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Guarda-Corpo Autoportante Inox',
    slug: 'guarda-corpo-autoportante',
    description:
      'Sistema autoportante com perfis de inox e vidro laminado. Instalação sem furação no piso.',
    shortDescription: 'Sistema autoportante, sem furação',
    category: ProductCategory.GUARDA_CORPO,
    priceType: PriceType.PER_M2,
    pricePerM2: 1390,
    colors: ['Incolor'],
    finishes: ['Inox Escovado'],
    thicknesses: ['12+12mm laminado'],
    isActive: true,
  },
  {
    name: 'Guarda-Corpo Spider',
    slug: 'guarda-corpo-spider',
    description: 'Sistema spider glass com fixadores pontuais. Design ultra minimalista e moderno.',
    shortDescription: 'Sistema spider, design minimalista',
    category: ProductCategory.GUARDA_CORPO,
    priceType: PriceType.PER_M2,
    pricePerM2: 1590,
    colors: ['Incolor', 'Low Iron'],
    finishes: ['Fixadores Inox'],
    thicknesses: ['12+12mm laminado'],
    isActive: true,
  },
  {
    name: 'Gradil de Inox',
    slug: 'gradil-inox',
    description:
      'Gradil em aço inox com ou sem vidro. Segurança e durabilidade para áreas externas.',
    shortDescription: 'Gradil inox, segurança e durabilidade',
    category: ProductCategory.GUARDA_CORPO,
    priceType: PriceType.PER_M2,
    pricePerM2: 890,
    colors: ['Natural'],
    finishes: ['Inox 304', 'Inox 316'],
    thicknesses: ['N/A'],
    isActive: true,
  },

  // ==================== DIVISÓRIAS (5 produtos) ====================
  {
    name: 'Divisória para Escritório',
    slug: 'divisoria-escritorio',
    description:
      'Divisória em vidro temperado 10mm com perfis de alumínio. Solução ideal para ambientes corporativos modernos.',
    shortDescription: 'Divisória vidro 10mm, ambientes corporativos',
    category: ProductCategory.DIVISORIAS,
    images: ['/images/products/divisoria.jpg'],
    thumbnail: '/images/products/divisoria.jpg',
    priceType: PriceType.PER_M2,
    pricePerM2: 690,
    priceRangeMin: 690,
    priceRangeMax: 990,
    colors: ['Incolor', 'Fumê', 'Jateado'],
    finishes: ['Perfil Alumínio', 'Perfil Preto'],
    thicknesses: ['10mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Divisória de Ambiente',
    slug: 'divisoria-ambiente',
    description: 'Divisória para separação de ambientes residenciais. Design limpo e funcional.',
    shortDescription: 'Divisória residencial, design limpo',
    images: ['/images/products/divisoria-ambiente.jpg'],
    thumbnail: '/images/products/divisoria-ambiente.jpg',
    category: ProductCategory.DIVISORIAS,
    priceType: PriceType.PER_M2,
    pricePerM2: 590,
    colors: ['Incolor', 'Fumê'],
    finishes: ['Perfil Alumínio'],
    thicknesses: ['8mm', '10mm'],
    isActive: true,
  },
  {
    name: 'Divisória Acústica',
    slug: 'divisoria-acustica',
    description:
      'Divisória com vidro laminado acústico. Isolamento de som para ambientes corporativos.',
    shortDescription: 'Divisória laminada acústica',
    category: ProductCategory.DIVISORIAS,
    priceType: PriceType.PER_M2,
    pricePerM2: 1290,
    colors: ['Incolor'],
    finishes: ['Perfil Alumínio Reforçado'],
    thicknesses: ['10+10mm acústico'],
    isActive: true,
  },
  {
    name: 'Divisória com Porta Integrada',
    slug: 'divisoria-com-porta',
    description:
      'Sistema completo de divisória com porta de vidro integrada. Solução turn-key para escritórios.',
    shortDescription: 'Divisória + porta integrada',
    category: ProductCategory.DIVISORIAS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 3500,
    priceRangeMax: 8500,
    colors: ['Incolor', 'Fumê'],
    finishes: ['Sistema Completo'],
    thicknesses: ['10mm'],
    isActive: true,
  },

  // ==================== PORTAS (11 produtos) ====================
  {
    name: 'Porta de Vidro de Correr',
    slug: 'porta-vidro-correr',
    description:
      'Porta de correr com vidro temperado e trilho superior. Design moderno e funcional para otimizar espaços.',
    shortDescription: 'Porta de correr, otimiza espaços',
    category: ProductCategory.PORTAS,
    images: ['/images/products/porta-correr.jpg'],
    thumbnail: '/images/products/porta-correr.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 2190,
    priceRangeMax: 3890,
    colors: ['Incolor', 'Fumê', 'Bronze', 'Jateado'],
    finishes: ['Trilho Superior', 'Puxadores Inox'],
    thicknesses: ['8mm', '10mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Porta de Abrir Inteiriça',
    slug: 'porta-abrir-inteirica',
    description: 'Porta de vidro temperado com abertura tradicional. Elegância e funcionalidade.',
    shortDescription: 'Porta de abrir tradicional',
    images: ['/images/products/porta-abrir-inteirica.jpg'],
    thumbnail: '/images/products/porta-abrir-inteirica.jpg',
    category: ProductCategory.PORTAS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 1890,
    priceRangeMax: 3290,
    colors: ['Incolor', 'Fumê'],
    finishes: ['Dobradiças Inox'],
    thicknesses: ['8mm', '10mm'],
    isActive: true,
  },
  {
    name: 'Porta Pivotante',
    slug: 'porta-pivotante',
    description: 'Porta pivotante em vidro temperado. Design sofisticado para entrada principal.',
    shortDescription: 'Porta pivotante, design sofisticado',
    category: ProductCategory.PORTAS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 3500,
    priceRangeMax: 6500,
    colors: ['Incolor', 'Fumê', 'Low Iron'],
    finishes: ['Sistema Pivotante Premium'],
    thicknesses: ['10mm', '12mm'],
    isActive: true,
  },
  {
    name: 'Porta Pivotante Premium',
    slug: 'porta-pivotante-premium',
    description: 'Porta pivotante top de linha com vidro especial e ferragens importadas.',
    shortDescription: 'Porta pivotante premium, ferragens importadas',
    category: ProductCategory.PORTAS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 8500,
    priceRangeMax: 15000,
    colors: ['Low Iron', 'Espelhado'],
    finishes: ['Ferragens Importadas'],
    thicknesses: ['12mm'],
    isActive: true,
  },
  {
    name: 'Porta Automática',
    slug: 'porta-automatica',
    description:
      'Porta automática com sensor e motor elétrico. Ideal para estabelecimentos comerciais.',
    shortDescription: 'Porta automática com sensor',
    category: ProductCategory.PORTAS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 5500,
    priceRangeMax: 12000,
    colors: ['Incolor'],
    finishes: ['Sistema Automático Completo'],
    thicknesses: ['10mm', '12mm'],
    isActive: true,
  },
  {
    name: 'Porta Camarão (Articulada)',
    slug: 'porta-camarao',
    description: 'Porta com abertura articulada tipo camarão. Economia de espaço com estilo.',
    shortDescription: 'Porta articulada tipo camarão',
    category: ProductCategory.PORTAS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 2690,
    priceRangeMax: 4290,
    colors: ['Incolor', 'Fumê'],
    finishes: ['Sistema Articulado'],
    thicknesses: ['8mm'],
    isActive: true,
  },

  // ==================== JANELAS (7 produtos) ====================
  {
    name: 'Janela Maxim-Ar de Vidro',
    slug: 'janela-maxim-ar',
    description:
      'Janela maxim-ar com vidro temperado e perfil de alumínio. Ventilação controlada e segura.',
    shortDescription: 'Janela maxim-ar, ventilação controlada',
    category: ProductCategory.JANELAS,
    images: ['/images/products/janela.jpg'],
    thumbnail: '/images/products/janela.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 890,
    priceRangeMax: 1690,
    colors: ['Branco', 'Preto', 'Bronze'],
    finishes: ['Alumínio Anodizado'],
    thicknesses: ['6mm'],
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Janela Basculante',
    slug: 'janela-basculante',
    description: 'Janela basculante em alumínio e vidro. Ideal para banheiros e cozinhas.',
    shortDescription: 'Janela basculante, ideal banheiros',
    category: ProductCategory.JANELAS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 790,
    priceRangeMax: 1490,
    colors: ['Branco', 'Preto'],
    finishes: ['Alumínio'],
    thicknesses: ['4mm', '6mm'],
    isActive: true,
  },
  {
    name: 'Janela de Correr',
    slug: 'janela-correr',
    description: 'Janela de correr com 2 ou 4 folhas. Sistema de trilho suave e silencioso.',
    shortDescription: 'Janela de correr, sistema suave',
    category: ProductCategory.JANELAS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 1290,
    priceRangeMax: 2890,
    colors: ['Branco', 'Preto', 'Bronze'],
    finishes: ['Trilho Alumínio'],
    thicknesses: ['6mm'],
    isActive: true,
  },
  {
    name: 'Janela Guilhotina',
    slug: 'janela-guilhotina',
    description: 'Janela guilhotina com abertura vertical. Design clássico e funcional.',
    shortDescription: 'Janela guilhotina, design clássico',
    category: ProductCategory.JANELAS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 1590,
    priceRangeMax: 2890,
    colors: ['Branco', 'Preto'],
    finishes: ['Alumínio Reforçado'],
    thicknesses: ['6mm'],
    isActive: true,
  },
  {
    name: 'Janela Pivotante',
    slug: 'janela-pivotante',
    description: 'Janela pivotante com eixo central. Ventilação e limpeza facilitadas.',
    shortDescription: 'Janela pivotante, ventilação facilitada',
    category: ProductCategory.JANELAS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 990,
    priceRangeMax: 1890,
    colors: ['Branco', 'Preto'],
    finishes: ['Sistema Pivotante'],
    thicknesses: ['6mm'],
    isActive: true,
  },

  // ==================== CORTINAS DE VIDRO (4 produtos) ====================
  {
    name: 'Cortina de Vidro Sistema Europeu',
    slug: 'cortina-vidro-europeu',
    description:
      'Cortina de vidro temperado com sistema de trilho europeu. Fechamento de sacadas com visual limpo.',
    shortDescription: 'Cortina vidro sistema europeu',
    images: ['/images/products/cortina-vidro-europeu.jpg'],
    thumbnail: '/images/products/cortina-vidro-europeu.jpg',
    category: ProductCategory.CORTINAS_VIDRO,
    priceType: PriceType.PER_M2,
    pricePerM2: 890,
    colors: ['Incolor'],
    finishes: ['Trilho Europeu'],
    thicknesses: ['8mm'],
    isActive: true,
  },
  {
    name: 'Cortina de Vidro Sistema Europeu Premium',
    slug: 'cortina-vidro-premium',
    description:
      'Sistema premium de cortina de vidro com trilho reforçado e vidro temperado de alta qualidade.',
    shortDescription: 'Cortina vidro premium, trilho reforçado',
    images: ['/images/products/cortina-vidro-premium.jpg'],
    thumbnail: '/images/products/cortina-vidro-premium.jpg',
    category: ProductCategory.CORTINAS_VIDRO,
    priceType: PriceType.PER_M2,
    pricePerM2: 1190,
    colors: ['Incolor', 'Fumê'],
    finishes: ['Trilho Premium'],
    thicknesses: ['10mm'],
    isActive: true,
  },
  {
    name: 'Cortina de Vidro Sistema Stanley',
    slug: 'cortina-vidro-stanley',
    description: 'Sistema Stanley de cortina de vidro. Qualidade internacional e durabilidade.',
    shortDescription: 'Sistema Stanley, qualidade internacional',
    images: ['/images/products/cortina-vidro-stanley.jpg'],
    thumbnail: '/images/products/cortina-vidro-stanley.jpg',
    category: ProductCategory.CORTINAS_VIDRO,
    priceType: PriceType.PER_M2,
    pricePerM2: 950,
    colors: ['Incolor'],
    finishes: ['Sistema Stanley'],
    thicknesses: ['8mm'],
    isActive: true,
  },
  {
    name: 'Cortina de Vidro Automatizada',
    slug: 'cortina-vidro-automatizada',
    description:
      'Cortina de vidro com abertura automatizada. Conforto e tecnologia para sua varanda.',
    shortDescription: 'Cortina automatizada, conforto e tecnologia',
    images: ['/images/products/cortina-vidro-automatizada.jpg'],
    thumbnail: '/images/products/cortina-vidro-automatizada.jpg',
    category: ProductCategory.CORTINAS_VIDRO,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 8500,
    priceRangeMax: 15000,
    colors: ['Incolor'],
    finishes: ['Sistema Automatizado'],
    thicknesses: ['10mm'],
    isActive: true,
  },

  // ==================== PERGOLADOS/COBERTURAS (6 produtos) ====================
  {
    name: 'Cobertura de Vidro Laminado',
    slug: 'cobertura-vidro-laminado',
    description:
      'Cobertura em vidro laminado com estrutura de alumínio ou aço. Proteção e beleza para áreas externas.',
    shortDescription: 'Cobertura laminada, proteção e beleza',
    images: ['/images/products/cobertura-vidro-laminado.jpg'],
    thumbnail: '/images/products/cobertura-vidro-laminado.jpg',
    category: ProductCategory.PERGOLADOS,
    priceType: PriceType.PER_M2,
    pricePerM2: 790,
    colors: ['Incolor', 'Verde'],
    finishes: ['Estrutura Alumínio', 'Estrutura Aço'],
    thicknesses: ['6+6mm laminado'],
    isActive: true,
  },
  {
    name: 'Cobertura Vidro Controle Solar',
    slug: 'cobertura-controle-solar',
    description: 'Cobertura com vidro de controle solar. Redução de calor e proteção UV.',
    shortDescription: 'Controle solar, reduz calor',
    category: ProductCategory.PERGOLADOS,
    priceType: PriceType.PER_M2,
    pricePerM2: 990,
    colors: ['Verde', 'Bronze', 'Cinza'],
    finishes: ['Estrutura Reforçada'],
    thicknesses: ['8+8mm laminado'],
    isActive: true,
  },
  {
    name: 'Pergolado com Estrutura Aço Inox',
    slug: 'pergolado-aco-inox',
    description: 'Pergolado com estrutura em aço inox e cobertura de vidro. Máxima durabilidade.',
    shortDescription: 'Pergolado inox, máxima durabilidade',
    images: ['/images/products/pergolado-aco-inox.jpg'],
    thumbnail: '/images/products/pergolado-aco-inox.jpg',
    category: ProductCategory.PERGOLADOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 12000,
    priceRangeMax: 35000,
    colors: ['Incolor', 'Verde'],
    finishes: ['Inox 304', 'Inox 316'],
    thicknesses: ['8+8mm laminado'],
    isActive: true,
  },

  // ==================== FECHAMENTOS (3 produtos) ====================
  {
    name: 'Fechamento de Área de Serviço',
    slug: 'fechamento-area-servico',
    description:
      'Fechamento em vidro para área de serviço. Mantém iluminação natural e protege de intempéries.',
    shortDescription: 'Fechamento área serviço, mantém iluminação',
    images: ['/images/products/fechamento-area-servico.jpg'],
    thumbnail: '/images/products/fechamento-area-servico.jpg',
    category: ProductCategory.FECHAMENTOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 2500,
    priceRangeMax: 6500,
    colors: ['Incolor', 'Fumê'],
    finishes: ['Sistema de Correr', 'Sistema Fixo'],
    thicknesses: ['6mm', '8mm'],
    isActive: true,
  },
  {
    name: 'Fechamento de Área Gourmet',
    slug: 'fechamento-area-gourmet',
    description:
      'Fechamento de área gourmet com vidro temperado. Integração de ambientes com proteção.',
    shortDescription: 'Fechamento gourmet, integração ambientes',
    images: ['/images/products/fechamento-area-gourmet.jpg'],
    thumbnail: '/images/products/fechamento-area-gourmet.jpg',
    category: ProductCategory.FECHAMENTOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 4500,
    priceRangeMax: 12000,
    colors: ['Incolor'],
    finishes: ['Sistema Sanfonado', 'Sistema de Correr'],
    thicknesses: ['8mm', '10mm'],
    isActive: true,
  },
  {
    name: 'Fechamento de Piscina',
    slug: 'fechamento-piscina',
    description: 'Fechamento de piscina em vidro temperado. Segurança para crianças e animais.',
    shortDescription: 'Fechamento piscina, segurança',
    category: ProductCategory.FECHAMENTOS,
    priceType: PriceType.PER_M2,
    pricePerM2: 650,
    colors: ['Incolor'],
    finishes: ['Vidro Temperado'],
    thicknesses: ['8mm', '10mm'],
    isActive: true,
  },

  // ==================== VIDROS ESPECIAIS (8 produtos) ====================
  {
    name: 'Vidro Extra Clear',
    slug: 'vidro-extra-clear',
    description: 'Vidro extra clear (baixo teor de ferro). Transparência máxima e cores reais.',
    shortDescription: 'Extra clear, transparência máxima',
    category: ProductCategory.VIDROS,
    priceType: PriceType.PER_M2,
    pricePerM2: 280,
    colors: ['Incolor'],
    finishes: ['Polido'],
    thicknesses: ['6mm', '8mm', '10mm', '12mm'],
    isActive: true,
  },
  {
    name: 'Vidro Jateado',
    slug: 'vidro-jateado',
    description: 'Vidro com acabamento jateado. Privacidade com passagem de luz natural.',
    shortDescription: 'Jateado, privacidade com luz',
    category: ProductCategory.VIDROS,
    priceType: PriceType.PER_M2,
    pricePerM2: 320,
    colors: ['Incolor'],
    finishes: ['Jateado Total', 'Jateado Parcial'],
    thicknesses: ['6mm', '8mm', '10mm'],
    isActive: true,
  },
  {
    name: 'Vidro Temperado 8mm',
    slug: 'vidro-temperado-8mm',
    description: 'Vidro temperado padrão 8mm. Segurança e resistência para diversas aplicações.',
    shortDescription: 'Temperado 8mm, segurança e resistência',
    category: ProductCategory.VIDROS,
    priceType: PriceType.PER_M2,
    pricePerM2: 180,
    colors: ['Incolor', 'Verde', 'Fumê', 'Bronze'],
    finishes: ['Temperado'],
    thicknesses: ['8mm'],
    isActive: true,
  },
  {
    name: 'Vidro Temperado 10mm',
    slug: 'vidro-temperado-10mm',
    description: 'Vidro temperado 10mm para aplicações que exigem maior resistência.',
    shortDescription: 'Temperado 10mm, maior resistência',
    category: ProductCategory.VIDROS,
    priceType: PriceType.PER_M2,
    pricePerM2: 220,
    colors: ['Incolor', 'Verde', 'Fumê'],
    finishes: ['Temperado'],
    thicknesses: ['10mm'],
    isActive: true,
  },
  {
    name: 'Vidro Laminado 8mm',
    slug: 'vidro-laminado-8mm',
    description: 'Vidro laminado 6+6mm. Segurança acústica e térmica.',
    shortDescription: 'Laminado 6+6mm, segurança acústica',
    category: ProductCategory.VIDROS,
    priceType: PriceType.PER_M2,
    pricePerM2: 280,
    colors: ['Incolor', 'Verde'],
    finishes: ['Laminado'],
    thicknesses: ['6+6mm'],
    isActive: true,
  },
  {
    name: 'Vidro Laminado Temperado',
    slug: 'vidro-laminado-temperado',
    description: 'Vidro laminado temperado. Máxima segurança para guarda-corpos e áreas críticas.',
    shortDescription: 'Laminado temperado, máxima segurança',
    category: ProductCategory.VIDROS,
    priceType: PriceType.PER_M2,
    pricePerM2: 420,
    colors: ['Incolor'],
    finishes: ['Laminado Temperado'],
    thicknesses: ['10+10mm'],
    isActive: true,
  },
  {
    name: 'Vidro Reflectivo',
    slug: 'vidro-reflectivo',
    description: 'Vidro reflectivo (espelhado). Controle solar e privacidade para fachadas.',
    shortDescription: 'Reflectivo, controle solar',
    category: ProductCategory.VIDROS,
    priceType: PriceType.PER_M2,
    pricePerM2: 250,
    colors: ['Prata', 'Bronze', 'Verde'],
    finishes: ['Reflectivo'],
    thicknesses: ['6mm', '8mm'],
    isActive: true,
  },
  {
    name: 'Vidro Serigrafado',
    slug: 'vidro-serigrafado',
    description:
      'Vidro com impressão serigráfica. Personalização e design para projetos especiais.',
    shortDescription: 'Serigrafado, personalização e design',
    category: ProductCategory.VIDROS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 350,
    priceRangeMax: 650,
    colors: ['Customizado'],
    finishes: ['Serigrafia'],
    thicknesses: ['6mm', '8mm', '10mm'],
    isActive: true,
  },

  // ==================== TAMPOS E PRATELEIRAS (4 produtos) ====================
  {
    name: 'Tampo de Vidro para Mesa',
    slug: 'tampo-vidro-mesa',
    description:
      'Tampo de vidro temperado com bordas polidas. Sob medida para sua mesa de jantar, centro ou aparador.',
    shortDescription: 'Tampo temperado sob medida',
    category: ProductCategory.TAMPOS_PRATELEIRAS,
    images: ['/images/products/tampo.jpg'],
    thumbnail: '/images/products/tampo.jpg',
    priceType: PriceType.PER_M2,
    pricePerM2: 380,
    priceRangeMin: 380,
    priceRangeMax: 580,
    colors: ['Incolor', 'Fumê', 'Bronze'],
    finishes: ['Bordas Polidas', 'Bordas Lapidadas', 'Bordas Bisotadas'],
    thicknesses: ['6mm', '8mm', '10mm', '12mm'],
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Tampo Extra Clear',
    slug: 'tampo-extra-clear',
    description: 'Tampo em vidro extra clear. Transparência absoluta para mesas de alto padrão.',
    shortDescription: 'Tampo extra clear, transparência absoluta',
    category: ProductCategory.TAMPOS_PRATELEIRAS,
    priceType: PriceType.PER_M2,
    pricePerM2: 480,
    colors: ['Extra Clear'],
    finishes: ['Bordas Polidas'],
    thicknesses: ['10mm', '12mm'],
    isActive: true,
  },
  {
    name: 'Prateleira de Vidro',
    slug: 'prateleira-vidro',
    description: 'Prateleira de vidro temperado com suportes metálicos. Funcionalidade e design.',
    shortDescription: 'Prateleira temperada, funcional',
    category: ProductCategory.TAMPOS_PRATELEIRAS,
    priceType: PriceType.FIXED,
    basePrice: 180,
    priceRangeMin: 180,
    colors: ['Incolor', 'Fumê'],
    finishes: ['Bordas Polidas'],
    thicknesses: ['6mm', '8mm'],
    isActive: true,
  },

  // ==================== FACHADAS (1 produto) ====================
  {
    name: 'Fachada de Vidro Comercial',
    slug: 'fachada-comercial',
    description:
      'Fachada estrutural com vidro de controle solar. Solução completa para projetos corporativos e comerciais.',
    shortDescription: 'Fachada estrutural, projetos corporativos',
    category: ProductCategory.VIDROS,
    images: ['/images/products/fachada.jpg'],
    thumbnail: '/images/products/fachada.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 15000,
    priceRangeMax: 50000,
    colors: ['Controle Solar', 'Refletivo', 'Incolor'],
    finishes: ['Sistema Estrutural', 'Spider Glass'],
    thicknesses: ['10mm', '12mm', '8+8mm laminado'],
    isActive: true,
    isFeatured: false,
  },

  // ==================== PAINÉIS DECORATIVOS (2 produtos) ====================
  {
    name: 'Painel Decorativo',
    slug: 'painel-decorativo',
    description:
      'Painel decorativo em vidro com ou sem impressão. Arte e funcionalidade para ambientes sofisticados.',
    shortDescription: 'Painel decorativo, arte e funcionalidade',
    category: ProductCategory.OUTROS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 1500,
    priceRangeMax: 5500,
    colors: ['Customizado'],
    finishes: ['Impressão Digital', 'Jateado Artístico'],
    thicknesses: ['8mm', '10mm'],
    isActive: true,
  },

  // ==================== KITS (10 produtos) ====================
  {
    name: 'Kit Box Frontal',
    slug: 'kit-box-frontal',
    description:
      'Kit completo para instalação de box frontal. Inclui perfis, vedações e acessórios.',
    shortDescription: 'Kit box frontal completo',
    category: ProductCategory.KITS,
    priceType: PriceType.FIXED,
    basePrice: 890,
    priceRangeMin: 890,
    colors: ['Branco', 'Preto', 'Alumínio'],
    finishes: ['Completo'],
    thicknesses: ['8mm'],
    isActive: true,
  },
  {
    name: 'Kit Box Elegance Completo',
    slug: 'kit-box-elegance',
    description:
      'Kit premium para box elegance. Ferragens de alta qualidade e acabamento perfeito.',
    shortDescription: 'Kit premium box elegance',
    images: ['/images/products/kit-box-elegance.jpg'],
    thumbnail: '/images/products/kit-box-elegance.jpg',
    category: ProductCategory.KITS,
    priceType: PriceType.FIXED,
    basePrice: 1590,
    priceRangeMin: 1590,
    colors: ['Preto Fosco', 'Cromado'],
    finishes: ['Premium'],
    thicknesses: ['10mm'],
    isActive: true,
  },
  {
    name: 'Kit Porta Pivotante VA',
    slug: 'kit-porta-pivotante',
    description: 'Kit para porta pivotante com sistema VA (vertical axis). Alta performance.',
    shortDescription: 'Kit porta pivotante VA',
    images: ['/images/products/kit-porta-pivotante.jpg'],
    thumbnail: '/images/products/kit-porta-pivotante.jpg',
    category: ProductCategory.KITS,
    priceType: PriceType.FIXED,
    basePrice: 2890,
    priceRangeMin: 2890,
    colors: ['Inox'],
    finishes: ['Sistema VA'],
    thicknesses: ['10mm', '12mm'],
    isActive: true,
  },
  {
    name: 'Kit Basculante/Maxim-Ar',
    slug: 'kit-basculante-maximar',
    description: 'Kit para janela basculante ou maxim-ar. Completo para instalação.',
    shortDescription: 'Kit janela basculante/maxim-ar',
    category: ProductCategory.KITS,
    priceType: PriceType.FIXED,
    basePrice: 390,
    priceRangeMin: 390,
    colors: ['Branco', 'Preto'],
    finishes: ['Alumínio'],
    thicknesses: ['6mm'],
    isActive: true,
  },
  {
    name: 'Kit Guarda-Corpo Residencial',
    slug: 'kit-guarda-corpo-residencial',
    description:
      'Kit completo para guarda-corpo residencial autoportante. Inclui perfis de alumínio, bottons de fixação e acessórios. Capacidade para vidro 10mm ou 12mm temperado.',
    shortDescription: 'Kit guarda-corpo autoportante residencial',
    category: ProductCategory.KITS,
    images: ['/images/products/kit-guarda-corpo.jpg'],
    thumbnail: '/images/products/kit-guarda-corpo.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 1890,
    priceRangeMax: 3200,
    colors: ['Alumínio Natural', 'Preto Fosco', 'Inox'],
    finishes: ['Autoportante'],
    thicknesses: ['10mm', '12mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Kit Fechamento Sacada Básico',
    slug: 'kit-fechamento-sacada-basico',
    description:
      'Kit econômico para fechamento de sacada pequena. Inclui trilhos, roldanas e acessórios para sistema de correr. Ideal para sacadas até 3m de largura.',
    shortDescription: 'Kit fechamento sacada econômico',
    category: ProductCategory.KITS,
    images: ['/images/products/kit-fechamento.jpg'],
    thumbnail: '/images/products/kit-fechamento.jpg',
    priceType: PriceType.FIXED,
    basePrice: 1290,
    priceRangeMin: 1290,
    colors: ['Branco', 'Alumínio'],
    finishes: ['Sistema Correr'],
    thicknesses: ['8mm'],
    isActive: true,
  },
  {
    name: 'Kit Prateleiras de Vidro (3un)',
    slug: 'kit-prateleiras-3un',
    description:
      'Kit com 3 prateleiras de vidro temperado 8mm (80x25cm cada). Inclui suportes metálicos cromados e parafusos de fixação. Perfeito para banheiro ou cozinha.',
    shortDescription: 'Kit 3 prateleiras 80x25cm com suportes',
    category: ProductCategory.KITS,
    images: ['/images/products/kit-prateleiras.jpg'],
    thumbnail: '/images/products/kit-prateleiras.jpg',
    priceType: PriceType.FIXED,
    basePrice: 590,
    priceRangeMin: 590,
    colors: ['Incolor'],
    finishes: ['Lapidado'],
    thicknesses: ['8mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Kit Espelhos Banheiro Completo',
    slug: 'kit-espelhos-banheiro',
    description:
      'Kit decorativo para banheiro: espelho bisotado 60x80cm + prateleira de vidro 60x15cm + suportes. Solução completa e elegante.',
    shortDescription: 'Kit espelho + prateleira para banheiro',
    category: ProductCategory.KITS,
    images: ['/images/products/kit-espelho-banheiro.jpg'],
    thumbnail: '/images/products/kit-espelho-banheiro.jpg',
    priceType: PriceType.FIXED,
    basePrice: 890,
    priceRangeMin: 890,
    colors: ['Incolor'],
    finishes: ['Bisotê 2cm'],
    thicknesses: ['4mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Kit Porta de Vidro Completo',
    slug: 'kit-porta-completo',
    description:
      'Kit all-in-one para porta de vidro: batente de alumínio, mola de piso, puxador 40cm inox, fechadura tetra e todos os acessórios. Só falta o vidro!',
    shortDescription: 'Kit porta: batente + mola + puxador + fechadura',
    category: ProductCategory.KITS,
    images: ['/images/products/kit-porta.jpg'],
    thumbnail: '/images/products/kit-porta.jpg',
    priceType: PriceType.FIXED,
    basePrice: 2190,
    priceRangeMin: 2190,
    colors: ['Alumínio', 'Preto Fosco'],
    finishes: ['Completo'],
    thicknesses: ['10mm'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Kit Box de Canto Econômico',
    slug: 'kit-box-canto-economico',
    description:
      'Kit para box de canto 90x90cm ou 80x80cm. Sistema de abertura simples com dobradiças. Inclui perfis, vedações e ferragens básicas. Ótimo custo-benefício.',
    shortDescription: 'Kit box canto 90x90 econômico',
    category: ProductCategory.KITS,
    images: ['/images/products/kit-box-canto.jpg'],
    thumbnail: '/images/products/kit-box-canto.jpg',
    priceType: PriceType.FIXED,
    basePrice: 690,
    priceRangeMin: 690,
    colors: ['Branco', 'Alumínio'],
    finishes: ['Básico'],
    thicknesses: ['8mm'],
    isActive: true,
  },

  // ==================== FERRAGENS/ACESSÓRIOS (2 produtos) ====================
  {
    name: 'Mola de Piso',
    slug: 'mola-piso',
    description: 'Mola de piso para portas de vidro. Fechamento suave e controlado.',
    shortDescription: 'Mola de piso, fechamento suave',
    category: ProductCategory.FERRAGENS,
    priceType: PriceType.FIXED,
    basePrice: 890,
    priceRangeMin: 890,
    colors: ['Inox'],
    finishes: ['Hidráulica'],
    thicknesses: ['N/A'],
    isActive: true,
  },
  {
    name: 'Puxador Tubular 40cm',
    slug: 'puxador-tubular-40cm',
    description: 'Puxador tubular em inox 40cm. Acabamento polido ou escovado.',
    shortDescription: 'Puxador tubular inox 40cm',
    category: ProductCategory.FERRAGENS,
    priceType: PriceType.FIXED,
    basePrice: 180,
    priceRangeMin: 180,
    colors: ['Inox'],
    finishes: ['Polido', 'Escovado', 'Preto Fosco'],
    thicknesses: ['N/A'],
    isActive: true,
  },

  // ==================== SERVIÇOS (25 produtos) ====================

  // --- INSTALAÇÃO (7 serviços) ---
  {
    name: 'Instalação de Box para Banheiro',
    slug: 'instalacao-box',
    description:
      'Serviço profissional de instalação de box para banheiro. Inclui medição técnica, instalação completa com nivelamento, vedação e ajustes finos. Garantia de 3 meses no serviço.',
    shortDescription: 'Instalação profissional de box com garantia',
    category: ProductCategory.SERVICOS,
    images: ['/images/products/instalacao.jpg'],
    thumbnail: '/images/products/instalacao.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 350,
    priceRangeMax: 800,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Instalação de Portas de Vidro',
    slug: 'instalacao-portas',
    description:
      'Instalação completa de portas de vidro temperado, incluindo batentes, ferragens, molas de piso e ajustes. Serviço especializado com garantia.',
    shortDescription: 'Instalação de portas de vidro com ferragens',
    category: ProductCategory.SERVICOS,
    images: ['/images/products/instalacao.jpg'],
    thumbnail: '/images/products/instalacao.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 400,
    priceRangeMax: 1200,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Instalação de Janelas de Vidro',
    slug: 'instalacao-janelas',
    description:
      'Instalação profissional de janelas de vidro temperado. Inclui vedação, ajustes de nivelamento e acabamento perfeito.',
    shortDescription: 'Instalação de janelas com vedação',
    category: ProductCategory.SERVICOS,
    images: ['/images/products/instalacao.jpg'],
    thumbnail: '/images/products/instalacao.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 300,
    priceRangeMax: 900,
    isActive: true,
  },
  {
    name: 'Instalação de Guarda-Corpo',
    slug: 'instalacao-guarda-corpo',
    description:
      'Instalação de guarda-corpo em vidro temperado ou estruturas metálicas. Serviço segue normas ABNT NBR 14718. Inclui fixação estrutural e testes de resistência.',
    shortDescription: 'Instalação segura conforme NBR 14718',
    category: ProductCategory.SERVICOS,
    images: ['/images/products/instalacao.jpg'],
    thumbnail: '/images/products/instalacao.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 800,
    priceRangeMax: 2500,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Instalação de Cortinas de Vidro',
    slug: 'instalacao-cortinas',
    description:
      'Instalação de cortinas de vidro para envidraçamento de sacadas e varandas. Sistema de trilhos premium com ajustes precisos.',
    shortDescription: 'Instalação de cortinas de vidro para sacadas',
    category: ProductCategory.SERVICOS,
    images: ['/images/products/instalacao.jpg'],
    thumbnail: '/images/products/instalacao.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 1200,
    priceRangeMax: 3500,
    isActive: true,
  },
  {
    name: 'Instalação de Espelhos',
    slug: 'instalacao-espelhos',
    description:
      'Serviço de instalação de espelhos com fixação segura. Inclui preparação de parede, colagem ou fixação com bottons, e acabamento.',
    shortDescription: 'Instalação segura de espelhos',
    category: ProductCategory.SERVICOS,
    images: ['/images/products/instalacao.jpg'],
    thumbnail: '/images/products/instalacao.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 150,
    priceRangeMax: 500,
    isActive: true,
  },
  {
    name: 'Instalação de Estruturas Metálicas',
    slug: 'instalacao-estruturas-metalicas',
    description:
      'Instalação profissional de estruturas metálicas em alumínio ou aço inox. Inclui montagem, nivelamento, fixação e acabamento. Serviço de serralheria especializado.',
    shortDescription: 'Instalação de estruturas metálicas',
    category: ProductCategory.SERVICOS,
    images: ['/images/products/instalacao.jpg'],
    thumbnail: '/images/products/instalacao.jpg',
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 600,
    priceRangeMax: 2800,
    isActive: true,
  },

  // --- MANUTENÇÃO (4 serviços) ---
  {
    name: 'Manutenção Preventiva',
    slug: 'manutencao-preventiva',
    images: ['/images/products/manutencao-preventiva.jpg'],
    thumbnail: '/images/products/manutencao-preventiva.jpg',
    description:
      'Manutenção preventiva completa de vidros, boxes, portas e janelas. Inclui limpeza de trilhos, lubrificação de ferragens, verificação de vedações e ajustes gerais.',
    shortDescription: 'Manutenção preventiva completa',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 200,
    priceRangeMax: 600,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Manutenção Corretiva',
    slug: 'manutencao-corretiva',
    images: ['/images/products/manutencao-corretiva.jpg'],
    thumbnail: '/images/products/manutencao-corretiva.jpg',
    description:
      'Serviço de manutenção corretiva para problemas em boxes, portas, janelas e outros produtos de vidro. Diagnóstico, reparo e ajustes necessários.',
    shortDescription: 'Reparo e correção de problemas',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 250,
    priceRangeMax: 1200,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Troca de Vidro Quebrado',
    slug: 'troca-vidro',
    images: ['/images/products/troca-vidro.jpg'],
    thumbnail: '/images/products/troca-vidro.jpg',
    description:
      'Serviço de troca de vidro quebrado ou danificado. Inclui remoção do vidro antigo, medição, fornecimento e instalação de vidro temperado novo.',
    shortDescription: 'Troca rápida de vidro quebrado',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 400,
    priceRangeMax: 1800,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Reparo de Ferragens',
    slug: 'reparo-ferragens',
    images: ['/images/products/manutencao-corretiva.jpg'],
    thumbnail: '/images/products/manutencao-corretiva.jpg',
    description:
      'Reparo ou substituição de ferragens danificadas: dobradiças, puxadores, fechaduras, roldanas e trilhos. Serviço rápido e eficiente.',
    shortDescription: 'Reparo de dobradiças, puxadores e roldanas',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 150,
    priceRangeMax: 700,
    isActive: true,
  },

  // --- REPAROS (5 serviços) ---
  {
    name: 'Ajuste de Portas de Vidro',
    slug: 'ajuste-portas',
    images: ['/images/products/manutencao-corretiva.jpg'],
    thumbnail: '/images/products/manutencao-corretiva.jpg',
    description:
      'Serviço de ajuste e regulagem de portas de vidro que estão emperrando, desalinhadas ou com problemas de fechamento. Inclui ajuste de dobradiças e molas.',
    shortDescription: 'Ajuste e regulagem de portas',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 180,
    priceRangeMax: 450,
    isActive: true,
  },
  {
    name: 'Ajuste de Janelas',
    slug: 'ajuste-janelas',
    images: ['/images/products/manutencao-corretiva.jpg'],
    thumbnail: '/images/products/manutencao-corretiva.jpg',
    description:
      'Ajuste de janelas de vidro com problemas de abertura/fechamento, infiltrações ou desalinhamento. Regulagem completa e troca de vedações se necessário.',
    shortDescription: 'Ajuste e vedação de janelas',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 150,
    priceRangeMax: 500,
    isActive: true,
  },
  {
    name: 'Conserto de Box',
    slug: 'conserto-box',
    images: ['/images/products/manutencao-corretiva.jpg'],
    thumbnail: '/images/products/manutencao-corretiva.jpg',
    description:
      'Reparo completo de boxes com problemas: trilhos emperrados, vedação com vazamento, roldanas quebradas, porta desalinhada. Diagnóstico e solução rápida.',
    shortDescription: 'Conserto completo de box',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 200,
    priceRangeMax: 800,
    isActive: true,
  },
  {
    name: 'Conserto de Portas de Alumínio',
    slug: 'conserto-portas-aluminio',
    images: ['/images/products/manutencao-corretiva.jpg'],
    thumbnail: '/images/products/manutencao-corretiva.jpg',
    description:
      'Serviço de serralheria para conserto de portas de alumínio: ajuste de batentes, troca de fechaduras, reparo de perfis danificados e pintura.',
    shortDescription: 'Serralheria - conserto portas alumínio',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 250,
    priceRangeMax: 900,
    isActive: true,
  },
  {
    name: 'Conserto de Janelas de Alumínio',
    slug: 'conserto-janelas-aluminio',
    images: ['/images/products/manutencao-corretiva.jpg'],
    thumbnail: '/images/products/manutencao-corretiva.jpg',
    description:
      'Reparo de janelas de alumínio: troca de roldanas, ajuste de trilhos, substituição de vidros, vedação e pintura de perfis.',
    shortDescription: 'Serralheria - conserto janelas alumínio',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 200,
    priceRangeMax: 750,
    isActive: true,
  },

  // --- SERRALHERIA (4 serviços) ---
  {
    name: 'Soldagem e Solda',
    slug: 'soldagem',
    images: ['/images/products/soldagem.jpg'],
    thumbnail: '/images/products/soldagem.jpg',
    description:
      'Serviço profissional de soldagem para estruturas metálicas, portões, gradis, guarda-corpos e estruturas em geral. Solda MIG, TIG e eletrodo. Acabamento de qualidade.',
    shortDescription: 'Soldagem profissional MIG/TIG',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 300,
    priceRangeMax: 1500,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Fabricação de Estruturas Metálicas',
    slug: 'fabricacao-estruturas',
    images: ['/images/products/soldagem.jpg'],
    thumbnail: '/images/products/soldagem.jpg',
    description:
      'Fabricação sob medida de estruturas metálicas em alumínio ou aço: portões, gradis, guarda-corpos, pergolados metálicos, escadas e estruturas personalizadas.',
    shortDescription: 'Fabricação sob medida de estruturas',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 1200,
    priceRangeMax: 5500,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Instalação de Portões e Gradis',
    slug: 'instalacao-portoes-gradis',
    images: ['/images/products/instalacao.jpg'],
    thumbnail: '/images/products/instalacao.jpg',
    description:
      'Instalação profissional de portões e gradis metálicos. Inclui fixação estrutural, ajuste de dobradiças/trilhos, motorização (se aplicável) e acabamento.',
    shortDescription: 'Instalação de portões e gradis',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 500,
    priceRangeMax: 2200,
    isActive: true,
  },
  {
    name: 'Pintura de Estruturas Metálicas',
    slug: 'pintura-metalica',
    images: ['/images/products/soldagem.jpg'],
    thumbnail: '/images/products/soldagem.jpg',
    description:
      'Serviço de pintura e acabamento para estruturas metálicas. Inclui preparação de superfície, aplicação de fundo anticorrosivo e pintura final. Cores variadas disponíveis.',
    shortDescription: 'Pintura e acabamento metálico',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 400,
    priceRangeMax: 1800,
    isActive: true,
  },

  // --- EMERGÊNCIAS (2 serviços) ---
  {
    name: 'Atendimento Emergencial 24h',
    slug: 'emergencia-24h',
    images: ['/images/products/emergencia.jpg'],
    thumbnail: '/images/products/emergencia.jpg',
    description:
      'Serviço de atendimento emergencial 24 horas para vidros quebrados, portas danificadas ou situações de risco. Resposta rápida e solução imediata.',
    shortDescription: 'Emergência 24h - atendimento rápido',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 500,
    priceRangeMax: 2500,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Troca Emergencial de Vidro',
    slug: 'troca-emergencial',
    images: ['/images/products/emergencia.jpg'],
    thumbnail: '/images/products/emergencia.jpg',
    description:
      'Troca urgente de vidro quebrado em até 24 horas. Serviço prioritário para situações de segurança ou emergência. Inclui medição, fornecimento e instalação.',
    shortDescription: 'Troca urgente em até 24h',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 600,
    priceRangeMax: 2200,
    isActive: true,
  },

  // --- MEDIÇÃO E ORÇAMENTO (3 serviços) ---
  {
    name: 'Medição Técnica',
    slug: 'medicao-tecnica',
    images: ['/images/products/medicao-tecnica.jpg'],
    thumbnail: '/images/products/medicao-tecnica.jpg',
    description:
      'Serviço de medição técnica profissional no local. Medidas precisas para fabricação de vidros, boxes, portas, janelas e estruturas sob medida.',
    shortDescription: 'Medição técnica profissional no local',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.FIXED,
    basePrice: 120,
    priceRangeMin: 120,
    priceRangeMax: 300,
    isActive: true,
  },
  {
    name: 'Orçamento In Loco',
    slug: 'orcamento-in-loco',
    images: ['/images/products/medicao-tecnica.jpg'],
    thumbnail: '/images/products/medicao-tecnica.jpg',
    description:
      'Visita técnica para elaboração de orçamento detalhado. Análise completa do projeto, medições e apresentação de soluções personalizadas.',
    shortDescription: 'Visita técnica e orçamento detalhado',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.FIXED,
    basePrice: 0,
    priceRangeMin: 0,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Consultoria Técnica',
    slug: 'consultoria-tecnica',
    images: ['/images/products/medicao-tecnica.jpg'],
    thumbnail: '/images/products/medicao-tecnica.jpg',
    description:
      'Consultoria técnica especializada para projetos de vidraçaria e serralheria. Orientação sobre materiais, normas técnicas, viabilidade e melhor solução para seu projeto.',
    shortDescription: 'Consultoria para projetos especiais',
    category: ProductCategory.SERVICOS,
    priceType: PriceType.QUOTE_ONLY,
    priceRangeMin: 200,
    priceRangeMax: 800,
    isActive: true,
  },
]

async function main() {
  console.log('🌱 Iniciando seed COMPLETO de produtos...')

  // Limpar produtos existentes
  await prisma.product.deleteMany({})
  console.log('✅ Produtos existentes removidos')

  // Criar produtos
  let count = 0
  for (const product of products) {
    await prisma.product.create({
      data: product,
    })
    count++
    console.log(`✅ [${count}/${products.length}] Criado: ${product.name}`)
  }

  console.log(`\n🎉 Seed concluído! ${products.length} produtos criados.`)

  // Estatísticas por categoria
  const stats = await prisma.product.groupBy({
    by: ['category'],
    _count: true,
  })

  console.log('\n📊 Produtos por categoria:')
  stats.forEach((stat) => {
    console.log(`   ${stat.category}: ${stat._count} produtos`)
  })
}

main()
  .catch((e) => {
    console.error('❌ Erro no seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
